### PR TITLE
No reseeding

### PR DESCRIPTION
**Pull request by pitdicker**
This is just hacked together in half an hour, to see what would happen if we remove `reseed` and all the reseeding machinery.

### CODE REVIEW

**Comment by pitdicker** [comment]
I have removed the second commit. Removing the `ReseedingRng` module is maybe a bit to enthusiastic.

**Comment by dhardy** [comment]
Thanks for separating the two changes out. Actually, it looks like you left a few of the reseeding changes in `thread_local`, remove them (for now at least) please?

It seems in general like removing `reseed` simplifies things nicely.

**Comment by pitdicker** [comment]
Do you think the changes to `tread-local` may not be the right direction, or do you just want to do the change to `reseed` first?

(Removed the commit b.t.w.)

**Comment by dhardy** [comment]
I'd just rather keep the stuff separate. Not sure about `ReseedingRng` yet; it may be useful to keep as is.

**Comment by dhardy** [comment]
Thanks; lets merge this!

**Pull request merged**
